---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goquorum-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: explorer.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quorum-explorer-explorer
                port:
                  number: 80
